version: '3'

networks:
# configuration for external traefik network
#  web:
#    external:
#       name: proxy_web
  internal:
      ipam:
          driver: default
          config:
              - subnet: 10.23.42.40/29

services:
  auth: # PSK Authentication Service
    build: ./docker-python/.
    command: python /code/auth.py
    volumes:
      - "./auth:/code"
    # set the PSK Password for the Auth Daemon here
    environment:
      - password=12345678
    networks:
        internal:
            ipv4_address: 10.23.42.42


  nginx-rtmp: # nginx rtmp server
    build: ./docker-nginx-rtmp/.
    ports:
      - "1935:1935"
    # if there is no proxy in front of this set your frontend port here
    # if you are using traefik instead set the configuration labels below
      - "8081:8080"
    volumes:
      - "./config/nginx-rtmp:/usr/local/nginx/conf"
      - "./videos:/videos"
    depends_on:
      - auth
    # these labels are for automatic configuration of traefik
    # labels:
    #  - "traefik.enable=true"
    #  - "traefik.backend=stream"
    #  - "traefik.frontend.rule=Host: stream.zom.bi"
    #  - "traefik.docker.network=proxy_web"
    #  - "traefik.port=8080"
    networks:
    # enable the web network for traefik
    #    web:
        internal:
            ipv4_address: 10.23.42.43


  frontend: # container for python frontend
    build: ./docker-python/.
    command: uwsgi uwsgi.ini
    volumes:
      - "./frontend:/code"
    networks:
        internal:
            ipv4_address: 10.23.42.44
